//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS01Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPMS01Entities : DbContext
    {
        public BPMS01Entities()
            : base("name=BPMS01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bridge> bridge { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<inspection_project> inspection_project { get; set; }
        public virtual DbSet<r_bridge_inspection_staff> r_bridge_inspection_staff { get; set; }
        public virtual DbSet<staff> staff { get; set; }
    }
}
