//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS01Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.inspection_project = new HashSet<inspection_project>();
        }
    
        public string id { get; set; }
        public string staff_id { get; set; }
        public string contract_no { get; set; }
        public string contract_name { get; set; }
        public decimal contract_amount { get; set; }
        public System.DateTime contract_signed_data { get; set; }
        public long contract_deadline { get; set; }
        public string contract_agmt_wk_cnt { get; set; }
        public string project_location { get; set; }
        public string delegation_client { get; set; }
        public string dlg_contactperson { get; set; }
        public string dlg_contactperson_phone { get; set; }
        public string accept_way { get; set; }
        public bool is_corporation_signed { get; set; }
        public bool is_client_signed { get; set; }
    
        public virtual staff staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inspection_project> inspection_project { get; set; }
    }
}
