//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS01Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspection_project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inspection_project()
        {
            this.r_bridge_inspection_staff = new HashSet<r_bridge_inspection_staff>();
        }
    
        public string id { get; set; }
        public string contract_id { get; set; }
        public string bridge_id { get; set; }
        public Nullable<System.DateTime> enter_date { get; set; }
        public Nullable<System.DateTime> exit_date { get; set; }
        public decimal bridge_inspection { get; set; }
    
        public virtual bridge bridge { get; set; }
        public virtual contract contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_bridge_inspection_staff> r_bridge_inspection_staff { get; set; }
    }
}
