//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS01Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_bridge_inspection_staff
    {
        public string id { get; set; }
        public string inspection_project_id { get; set; }
        public string 职工_id { get; set; }
        public bool is_response { get; set; }
        public bool scene_coff { get; set; }
        public bool plan_coff { get; set; }
        public bool report_coff { get; set; }
        public bool report_check_coff { get; set; }
        public bool others_coff { get; set; }
        public Nullable<double> production_value_ratio { get; set; }
        public Nullable<double> production_value { get; set; }
    
        public virtual inspection_project inspection_project { get; set; }
        public virtual staff staff { get; set; }
    }
}
