//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS01Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.contract = new HashSet<contract>();
            this.r_bridge_inspection_staff = new HashSet<r_bridge_inspection_staff>();
        }
    
        public string id { get; set; }
        public decimal staff_no { get; set; }
        public string staff_password { get; set; }
        public string staff_name { get; set; }
        public decimal gender { get; set; }
        public string office_phone { get; set; }
        public string mobile_phone { get; set; }
        public string position { get; set; }
        public string job_title { get; set; }
        public string education { get; set; }
        public System.DateTime hiredate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_bridge_inspection_staff> r_bridge_inspection_staff { get; set; }
    }
}
